[Unit]
After=lldpd.service systemd-user-sessions.service network-online.target
Requires=lldpd.service
Wants=network-online.target

[Service]
ExecStart=
ExecStart=-/usr/local/bin/lldp-display.sh
StandardInput=tty
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
Restart=always
RestartSec=3