#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: dhcp-config <interface>"
    echo "Example: dhcp-config eth0"
    echo ""
    echo "Remove DHCP:"
    echo "  dhcpcd -k eth0"
    echo "  ip addr flush dev eth0"
    exit 1
fi

IFACE=$1

if ! ip link show "$IFACE" >/dev/null 2>&1; then
    echo "Error: Interface $IFACE does not exist"
    echo "Available interfaces:"
    ip -o link show | awk -F': ' '{print "  " $2}'
    exit 1
fi

echo "Configuring $IFACE with DHCP..."
ip link set "$IFACE" up
dhcpcd "$IFACE"
echo "Done. Check with: ip addr show $IFACE"
