#!/bin/bash

if [ -z "$2" ]; then
    echo "Usage: vlan-create <parent_interface> <vlan_id>"
    echo "Example: vlan-create eth0 100"
    echo ""
    echo "Remove VLAN:"
    echo "  ip link del eth0.100"
    echo ""
    echo "List VLANs:"
    echo "  ip -d link show type vlan"
    exit 1
fi

PARENT=$1
VLAN_ID=$2
VLAN_IFACE="${PARENT}.${VLAN_ID}"

modprobe 8021q 2>/dev/null
echo "Creating VLAN $VLAN_ID on $PARENT..."
ip link add link $PARENT name $VLAN_IFACE type vlan id $VLAN_ID
ip link set $VLAN_IFACE up
echo "Done. VLAN interface: $VLAN_IFACE"
echo "Configure with: static-ip $VLAN_IFACE <ip/mask> <gateway>"
echo "           or: dhcp-config $VLAN_IFACE"